### ISSUE TITLE
layout problem with TouchUI

### ISSUE THREAD

**Issue by n2hpz** [jneilliii/OctoPrint-ConsolidatedTabs#14]
I use OcotPrint on both my PC monitor and a 3.5 inch screen on my printer.  I love the layout capabilities on my PC, but as soon I set up multiple tabs on my PC it makes the 3.5 inch screen useless.  The 3.5 inch screen is running TouchUI.  It would be great if there was a way to disable Consolidated Tabs for the small screen.

**Comment by jneilliii** [comment]
I can definitely do that. I've had to deal with TouchUI before and disabling stuff when that was loaded and enabled. I thought that was in this plugin already, but I must have not done that.

**Comment by n2hpz** [comment]
I just tried again.  Even did a total reboot of the pi.  No luck.

**Comment by n2hpz** [comment]
Just to confirm, I shrunk my pc browser window as narrow as it would go and refreshed the webpage.  It switched to the TouchUI layout with the same error.
![PC_narrow](https://user-images.githubusercontent.com/69761535/91110396-b8778e00-e64b-11ea-9baa-20a2255b88ad.jpg)

**Comment by jneilliii** [comment]
Thanks, that's one thing I didn't try. What is the resolution of your pi's touch screen?

**Comment by jneilliii** [comment]
I think I got it now. Was able to reproduce by mimicking a hyperpixel display in developer console. If you reinstall with that same URL above it should work better.

![image](https://user-images.githubusercontent.com/5249455/91114149-38562600-e655-11ea-93af-51d106af2a28.png)

**Comment by n2hpz** [comment]
that did it!!!!!!!!!!!!!!!

**Comment by jneilliii** [comment]
Awesome. I just made a couple of more tweaks and will push an official version release now that you've confirmed. Thanks for the testing.
