### ISSUE TITLE
Can no longer resize or move tabs

### ISSUE THREAD

**Issue by SeanDolan** [jneilliii/OctoPrint-ConsolidatedTabs#15]
Everything was working fine up until I went to the latest version today that adds the full browser width. With that option on or off, I no longer can drag or resize tabs. I am also not able to specify a size if I don't have full browser width ticked. The plugin seems to basically only allow ordering top to bottom now of the tabs on one screen and only way to change the order is via settings.

No drop and drag or resize at all anymore :(

**Comment by jneilliii** [comment]
Read release notes, and the readme. Switched to shift+click activation for enabling those.
