### ISSUE TITLE
Issue with G Code Viewer Plug in

### ISSUE THREAD

**Issue by miobx** [jneilliii/OctoPrint-ConsolidatedTabs#16]
I have the g-code plug in and when I pass the mouse pointer over the screen area for the g code viewer the it grams the grid and moves it around util you pas out of the g code viewer window space.

**Comment by jneilliii** [comment]
Yeah, not sure if I can fix this because it's the viewer itself that is moving the page.

**Comment by jneilliii** [comment]
Do you know if this issue still exists for you in the latest 1.0.0+ versions that implements gridstack.

**Comment by miobx** [comment]
Hi,
No I have not had any of these problems in the latest release.







Regards,

Mark Faunce

313 610-4271
