### ISSUE TITLE
Tabs missing resize or move controls

### ISSUE THREAD

**Issue by captdistraction** [jneilliii/OctoPrint-ConsolidatedTabs#17]
I've been unable to resize consolidated tabs, I've tried limiting which plugins are installed, haven't spent much time in the browser consoles to see if there's a specific error yet, but wanted to make sure I wasn't missing anything simple. I had themify installed, but removed it in case it was preventing the display of those controls/CSS

![image](https://user-images.githubusercontent.com/66377777/90442878-2e9a5480-e090-11ea-9319-33f4eb934fb2.png)

installed plugins
![image](https://user-images.githubusercontent.com/66377777/90442944-4d005000-e090-11ea-9d17-cae86678bcaf.png)

**Comment by sudo-lelek** [comment]
same here

**Comment by jneilliii** [comment]
Hold down the shift key and click on a panel. That activates the panel and allows moving and resizing, as documented in the release notes, and in Tips on the readme. I will be adding it to the settings page as well in the next release and on the official plugin repository listing soon to avoid further confusion.

**Comment by captdistraction** [comment]
confirmed, I'm an idiot user :) Thanks for the fast response
