### ISSUE TITLE
Control tab with fullscreen webcam plugin installed does not work when is used in a consolidated tabs plugin

### ISSUE THREAD

**Issue by LarryVand** [jneilliii/OctoPrint-ConsolidatedTabs#21]
Control tab with fullscreen webcam plugin installed does not work when is used in a consolidated tabs plugin.

To see the issue, have control tab alone (NOT in a consolidated tabs window), and if you double click the webcam it goes to full screen. Then put the control tab in a consolidated tabs window and if you double click the webcam nothing happens. And the webcam fullscreen does not work in a consolidated tab, even if the control tab is the ONLY ONE in the consolidated tabs window.

I'm posting this to both places just so the two authors of the 2 plugins are aware of the incompatibility.

**Comment by LarryVand** [comment]
Let me try and remove the ArduCam focus plugin and see if that works...Nope. Removing the ArduCam focus and still fullscreen has the issue in Consolidated tabs. 

I'll try the 0.1.1 version and let you know... SUCCESS!!!! The non-blocking img tag you added did the trick. Awesome job!

**Comment by jneilliii** [comment]
That's strange that it was working for me, but glad that sorted it out for you.

**Comment by LarryVand** [comment]
Maybe you already were running a version that had the non-blocking img tag already? Who knows. I used to be in the IT fields 20 years ago and the dependencies were so many in windows and networking to try and fix bugs, that it drove me crazy and made me switched fields because of it.
