### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by NovaViper** [jneilliii/OctoPrint-ConsolidatedTabs#28]
Hi, Im using the plugin along with Themify and I notice that the items within the Consolidated tabs have a white background and do not match up with the themes within Themify. I'm using Octoprint 1.4.2
![image](https://user-images.githubusercontent.com/7191115/94596601-fa4eb200-0251-11eb-9ff5-e612e4650e94.png)

**Comment by jneilliii** [comment]
Read the docs. There are pointer on how to do this in Themeify's advanced section and is how I do it...

**Comment by jneilliii** [comment]
Specifically here...
https://github.com/jneilliii/OctoPrint-ConsolidatedTabs#themeify

**Comment by jneilliii** [comment]
and here's an exert from my Themeify settings for reference.
```
        -   enabled: true
            rule: background-color
            selector: div.panel-heading
            value: '#2f3136'
        -   enabled: true
            rule: border-bottom
            selector: div.panel-heading
            value: '1px solid #fc8003'
        -   enabled: true
            rule: border
            selector: div.panel
            value: '1px solid #fc8003'
        -   enabled: true
            rule: background-color
            selector: div.panel
            value: '#2f3136'
```

**Comment by NovaViper** [comment]
Ah, cool. Thanks!
