### ISSUE TITLE
MultiCam plugin Not working

### ISSUE THREAD

**Issue by corautem** [jneilliii/OctoPrint-ConsolidatedTabs#31]
Hi, first thing thank you for your splendid work. 
 I'm using two cameras connected to Octoprint using MultiCam plugin ( https://github.com/mikedmor/OctoPrint_MultiCam ) but after I installed ConsolidatedTabs I can't switch cameras anymore, any ideas?
 Thank you

**Comment by jneilliii** [comment]
duplicate of #20, I submitted a PR to that repo to resolve the issue, it was merged, but the plugin author did not release a new version yet with those changes in them. If you uninstall that plugin and install it fresh it should have the changes included.
