### ISSUE TITLE
[BUG]: No selectable tabs in plugin configuration menu

### ISSUE THREAD

**Issue by Andoramb** [jneilliii/OctoPrint-ConsolidatedTabs#37]
**Describe the bug**
Hi, I've just installed the plugin, but I cannot see any tabs to pick from on the config page
Am I missing something?
I cannot see any errors in the dev.console, I tried to disable themefy also

Thanks for the plugin :)
![image](https://user-images.githubusercontent.com/3399628/101085523-d4c28980-35af-11eb-93f0-bb013aaff8fb.png)

**Comment by jneilliii** [comment]
Disable Custom Control Editor, there is a conflicting sortable library in that one. You shouldn't lose your customizations, as that's part of core OctoPrint functionality.

**Comment by Andoramb** [comment]
That's right, it was time for some cleanup. Works like a charm.
Thanks!
