### ISSUE TITLE
[FR]: Space between panels when snap feature enabled

### ISSUE THREAD

**Issue by feuerwasser85** [jneilliii/OctoPrint-ConsolidatedTabs#42]
It would be great when ther were an option for adjustable space between panels when the snap feature is enabled. Looks more clean then panels sticked together.

**Comment by jneilliii** [comment]
You might want to test out my current development version. You can copy/paste the URL below into Plugin Manager > Get More > ...from URL and clicking install over your existing version. You will have to setup the consolidated tabs again, but it's done a little different in this version. There's an edit button you click on the tab, that will then put + signs next to tab names. Click those and it will add the tabs to the consolidated one. Would love to get some feedback.

```
https://github.com/jneilliii/OctoPrint-ConsolidatedTabs/archive/develop/gridstack.zip
```
