### ISSUE TITLE
[BUG]: Edit button disappearing after initial setup

### ISSUE THREAD

**Issue by R1N4x** [jneilliii/OctoPrint-ConsolidatedTabs#47]
First of: I love the Plug-In.

But there is a weird bug. 
After I've set up the first layout and saved it, the edit button disappeared. (I've checked the settings!) 

I found the reason why: the button has the CSS style "Display: none" (See screenshot)

![image](https://user-images.githubusercontent.com/29910692/111707236-f9333080-8843-11eb-8ad5-962d97067986.png)

Running OctoPrint 1.5.3 and Python 3.7.3

**Comment by jneilliii** [comment]
can you test with the latest rc version. I think this is a conflict with another plugin that I've already fixed.

**Comment by jneilliii** [comment]
actually, sorry that was a different issue that I fixed. Could you check the developer console of your browser though and see if there are any errors on initial page load please.

**Comment by R1N4x** [comment]
Sure, here you go: 

![image](https://user-images.githubusercontent.com/29910692/111757765-f7955700-889b-11eb-99f4-e1616c73306e.png)

(For testing I disabled all Plug-Ins but yours)

**Comment by R1N4x** [comment]
> can you test with the latest rc version. I think this is a conflict with another plugin that I've already fixed.

Installing 1.0.1rc1 fixed it.

**Comment by jneilliii** [comment]
Ok cool. It was the error that I fixed for people that don't have webcams.
