### ISSUE TITLE
[BUG]: ConsolidatedTabs issue with PrettyGcode plugin Dashboard/State/File Windows in Full Screen mode

### ISSUE THREAD

**Issue by LarryVand** [jneilliii/OctoPrint-ConsolidatedTabs#49]
**Describe the bug**
With ConsolidatedTabs (CT) and PrettyGCode (PGC) plugins installed, toggle PGC to full screen and try clicking the Dashboard/State/File buttons. Nothing happens. But disable ConsolidatedTabs plugin and the Dashboard/State/File buttons work just fine. This used to work on prior versions so clearly something changed.

**Expected behavior**

**Screenshots**

**Browser errors**
<!-- Please check the developer console of your browser (F12) for errors on initial page load. Include those errors here if there are any.

**Comment by jneilliii** [comment]
Something must have changed since #38 was resolved. I assume you cross posted an issue on their plugin as well?

**Comment by LarryVand** [comment]
Not yet, but I'm about to.

**Comment by jneilliii** [comment]
Hey @LarryVand is the Pretty GCode tab consolidated or not?

**Comment by LarryVand** [comment]
No it is not. It is in its own tab.

**Comment by jneilliii** [comment]
I've just release version 1.0.2rc1 for you to test with. Change the plugin's release channel to `Release Candidate` in OctoPrint's Software Update settings and click update when prompted.

**Comment by LarryVand** [comment]
> I've just release version 1.0.2rc1 for you to test with. Change the plugin's release channel to `Release Candidate` in OctoPrint's Software Update settings and click update when prompted.

Yup, it's fixed. Many thanks for all your work.

**Comment by LarryVand** [comment]
The issue is closed.
