### ISSUE TITLE
[FR]: Deselect Tabs

### ISSUE THREAD

**Issue by ArtemioPadilla** [jneilliii/OctoPrint-ConsolidatedTabs#56]
**Is your feature request related to a problem? Please describe.**
Selected tabs cannot be deselected and some do not work in the consolidated tabs view, so they are rendered useless.

**Describe the solution you'd like**
Add button to deselect tabs once in the consolidated view.

**Describe alternatives you've considered**
I've reviewed some docs but couldn't find this information

**Comment by jneilliii** [comment]
In edit mode you can drag the panel out of the tab and it will remove it from being consolidated.

**Comment by ArtemioPadilla** [comment]
Thanks for your reply good man
