### ISSUE TITLE
[BUG]: Pencil/Edit Icon Not Appearing on Toolbar

### ISSUE THREAD

**Issue by roomonthethird** [jneilliii/OctoPrint-ConsolidatedTabs#57]
**Describe the bug**
Hello!

I downloaded Consolidated Tabs and do not see the edit button.

I see someone else had a similar issue in Issue #50 but I did not see any steps how to fix the issue.

I checked on and off different settings within the plugin and did not notice any change to the issue.

Things I tried to solve the issue:
- I ran Octoprint in [Safe Mode](http://docs.octoprint.org/en/master/features/safemode.html) and this did not solve the issue.
- I turned off all plug ins by process of elimination to see if that would affect anything. No change.
- I cleaned up the data (eraser button) of all third party plug ins. No change.
- Tried running Octoprint in Firefox (primary use browser), Chrome and Safari. All instances experienced the same issue.

**Expected behavior**
There should be a pencil icon in the navbar that allows me to edit the consolidated tabs plugin.

**Screenshots**
![Screenshot 2023-11-21 101453](https://github.com/jneilliii/OctoPrint-ConsolidatedTabs/assets/118706194/ba4e7358-086b-46b4-a171-5369c795cc6d)

**Browser errors**
![Screenshot 2023-11-21 101735](https://github.com/jneilliii/OctoPrint-ConsolidatedTabs/assets/118706194/90cab42a-7c51-4fd6-8781-a1f9a6897452)
![Screenshot 2023-11-21 101749](https://github.com/jneilliii/OctoPrint-ConsolidatedTabs/assets/118706194/b88c6065-de58-4d2f-b096-5a705ee54eb0)

**Extra Info**
    OctoPrint version 1.9.3
    OctoPi* 0.18.0 (build 2022.01.20.12925)
    Python 3.7.3
    Heavily modded Ender 3 with a BIGTREETECH SKR Mini E3 V1.2 board
    Marlin 2.32 from TH3D
    Firefox, Chrome, Safari
    Windows 10 and macOS Ventura 13.6.2

edit: 
Although the issue persists in SafeMode, I wanted to give:
List of All Plugins that I have:
- Bed Visualizer - active
- Camera Settings - active
- Change Filament - disabled
- Classic Webcam - active
- Consolidated Tabs - active
- Dashboard - active
- Display Layer Progress - disabled
- Detailed Progress - active
- Dragon Order - active
- FileManager - active
- Firmware Check -  active
- Firmware Updater - active
- HeaterTimeout - active
- Obico - active
- Octolapse - active
- OctoPod - active
- Power Failure Recovery - disabled
- Preheat Button - active
- PrettyGCode - active
- PrintTimeGenius - active
- Simple Emergency Stop - active
- Slicer Thumbnails - active
- SmartABL - disabled
- UI Customizer - active
- Webcam Extras - active

**Comment by jneilliii** [comment]
The error you show is pretty gcode based. The edit button only shows when the consolidated tab is active.

**Comment by roomonthethird** [comment]
🤦 
Thank you so much, sorry for the dumb post!
