### ISSUE TITLE
Compatibility with Themeify plugin

### ISSUE THREAD

**Issue by pszeder** [jneilliii/OctoPrint-ConsolidatedTabs#7]
I use the Themeify plugin to make the UI more eye friendly. 
The CSS of this plugin causes the backgrounds of the consolidated tabs to be white, with the texts hard to read. Tool has mouse over it. 

![image](https://user-images.githubusercontent.com/57759320/89636441-8a9af700-d8a0-11ea-96b8-deb79e05972d.png)

For the time being I've removed the line for the background of the .panel and .panel-heading in CSS to have this: 

![image](https://user-images.githubusercontent.com/57759320/89637328-e7e37800-d8a1-11ea-8273-8773ffe3da15.png)

I think this could be a good and quick fix which would work with the other themes too, but of course, would change the look without Themeify. Another possibility would be to fix it in Themeify, but I'm not sure what their opinion is, other than try to not set colours in other plugins.

**Comment by jneilliii** [comment]
You just need to add your own advanced options...

![image](https://user-images.githubusercontent.com/5249455/89662187-b79bd980-d8a1-11ea-9dbe-b630efc733fb.png)

Relevant css selectors...

![image](https://user-images.githubusercontent.com/5249455/89662331-ec0f9580-d8a1-11ea-8f2f-c402fdde3d06.png)

**Comment by jneilliii** [comment]
Added the above tips to the readme.

**Comment by pszeder** [comment]
I came across advanced options of Themeify after submitting this issue, but didn't think it would be the preferred way as it's not something an average user can do. Anyway having it in the readme will at least give them a chance to set it up correctly.
